---
title: "p8105_hw3_yz4982"
author: "Yuanyuan Zhang"
output:
  github_document: default
--- 

Promblem 1
------------------------------------------------------------
### Library
```{r}
library(tidyverse)
library(p8105.datasets)
library(forcats) 
library(janitor)
library(lubridate)

data("instacart")
```

### Description
```{r}
n_rows <- nrow(instacart)
n_cols <- ncol(instacart)

n_users       <- n_distinct(instacart$user_id)
n_orders      <- n_distinct(instacart$order_id)
n_products    <- n_distinct(instacart$product_id)
n_aisles      <- n_distinct(instacart$aisle)

cat(
  "rows:", n_rows,
  "columns:", n_cols, "\n",
  "unique users:", n_users,
  "unique orders:", n_orders, "\n",
  "unique products:", n_products,
  "unique aisles:", n_aisles, "\n"
)

# check variables and type
# glimpse(instacart)

# key varibles
set.seed(8105)
instacart |> 
  select(order_id, user_id, product_id, product_name, aisle, department, 
         add_to_cart_order, reordered, order_dow, order_hour_of_day) |>
  slice_sample(n = 5)

```

### Number of Aisles
```{r}
# Counting the number of products ordered per aisle
aisle_counts <- instacart |>
  count(aisle, name = "n_items") |>
  arrange(desc(n_items))

# Total aisle 
n_aisles <- nrow(aisle_counts)
n_aisles

# Top 5 most ordered aisles
top_aisles <- aisle_counts |> slice_max(n_items, n = 5)
top_aisles
```

### Plot The Number of Items Ordered in Each Aisle
```{r}
plot_df <- aisle_counts |>
  filter(n_items > 10000) |>
  mutate(aisle = fct_reorder(aisle, n_items))

p <- ggplot(plot_df, aes(x = n_items, y = aisle)) +
  geom_col() +
  labs(
    title = "Number of items ordered by aisle (> 10,000)",
    x = "Items ordered",
    y = "Aisle"
  )

ggplot2::ggsave(
  filename = "Figures/aisle_items_over_10k.png",
  plot = p,
  width = 8, height = 5, units = "in", dpi = 300
)

print (p)
```

### Table of Top 3 Popular Items in Each of The Aisles 
```{r}
top3_tbl <- instacart |>
  # Keep only rows from these three aisles
  filter(aisle %in% c("baking ingredients",
                      "dog food care",
                      "packaged vegetables fruits")) |>
  # Count
  count(aisle, product_name, name = "times_ordered", sort = TRUE) |>
  # Make group
  group_by(aisle) |>
  # Take the top 3 products each aisle
  slice_max(times_ordered, n = 3) |>
  # Order by aisle
  arrange(aisle, desc(times_ordered)) |>
  # Assign ranks
  mutate(rank_in_aisle = row_number()) |>
  select(aisle, rank_in_aisle, product_name, times_ordered) |>
  ungroup()

# Print
top3_tbl
```

### Mean Hour of The Day
```{r}
mean_hour_tbl <- instacart |>
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) |>
  mutate(
    # Instacart encodes convert
    day_convert = factor(order_dow, levels = 0:6,
                 labels = c("Sun","Mon","Tue","Wed","Thu","Fri","Sat"))
  ) |>
  # Make group
  group_by(product_name, day_convert) |>
  # Calculate the mean
  summarise(mean_hour = mean(order_hour_of_day), .groups = "drop") |>
  # Make 2*7 table
  tidyr::pivot_wider(names_from = day_convert, values_from = mean_hour) |>
  rename(Product = product_name)

# Print
mean_hour_tbl
```

Promblem 2
------------------------------------------------------------
### Import Data
```{r}
zip_code_df = 
  read_csv("p8105_hw3_yz4982_files/zillow_data/Zip Codes.csv", 
           na = c("NA", ".", ""))

# check variables and type
glimpse(zip_code_df)


zori_raw = 
  read_csv("p8105_hw3_yz4982_files/zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", 
           na = c("NA", ".", ""))

# Check variables and type
# glimpse(zip_code_df)
# glimpse(zori_raw )
```

### Clean Data
```{r}

zori_long <- zori_raw |>
  rename(zip = RegionName) |>
  pivot_longer(
    cols = matches("^\\d{4}-\\d{2}-\\d{2}$"),
    names_to = "month",
    values_to = "zori"
  ) |>
  mutate(month = lubridate::ymd(month)) |>
  # keep only 2015-01-31 to 2024-08-31
  filter(month >= ymd("2015-01-31"),
         month <= ymd("2024-08-31"))
```

### Statisic Calculate
```{r}
zip_month_counts <- zori_long |>
  group_by(zip) |>
  summarise(months_observed = sum(!is.na(zori)), .groups = "drop")

# ZIP codes are observed 116 times
n_exact_116 <- sum(zip_month_counts$months_observed == 116)

# Observed fewer than 10 times
n_fewer_10  <- sum(zip_month_counts$months_observed < 10)

# Print
cat("ZIP codes are observed 116 times：", n_exact_116, "\n")
cat("Observed fewer than 10 times：", n_fewer_10, "\n")
```

Why are some ZIP codes are observed rarely and others observed in each month?


### Reader-friendly Table 
```{r}

```
